name: Bug Report
description: File a bug
title: Bug Report
body:
  - type: input
    id: "winver"
    attributes:
      label: "Windows version"
      description: "What **Windows version** are you running?"
      placeholder: "e.g, Windows 11"
    validations:
      required: true 
  - type: input
    id: "appver"
    attributes:
      label: "App version"
      description: "What version of **HTTP Utility** are you running?"
      placeholder: "e.g, v1.0.0"
    validations:
      required: true 
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1. Go to ...
        2. Scroll to ...
        3. Click on ...
        ...
    validations:
      required: true
  - type: dropdown
    id: frequency
    attributes:
      label: How often does this bug occur?
      options:
        - Very rarely
        - Rarely
        - Middle
        - Often
        - Very often
    validations:
      required: true
